In [2]:
import cv2
import numpy as np

In [6]:
np.int16(np.array([[1,2,3],[3,4,5]],np.uint8)/4)

array([[0, 0, 0],
       [0, 1, 1]], dtype=int16)

In [10]:
np.int16([(790, 898), (470, 1080), (1610, 1080), (1290, 898)])/4

array([[197.5, 224.5],
       [117.5, 270. ],
       [402.5, 270. ],
       [322.5, 224.5]])

In [11]:
a = (3,2)

In [13]:
x = 32 /3 
y = 32/11

In [14]:
a = (x,y)

In [22]:
np.int16(np.array([[(790, 898), (470, 1080), (1610, 1080), (1290, 898)]])/4)

array([[[197, 224],
        [117, 270],
        [402, 270],
        [322, 224]]], dtype=int16)

In [1]:
import numpy as np
import cv2

def print_cordinate(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(img[y, x])
        print(x, y)

img = cv2.imread('C:/Users/junho/HEVEN-AutonomousCar-2019/HENVEN_PathPlanning/Integration/module_jihoon/test_Moment.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
img = cv2.resize(img, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_AREA)
print(img.shape[:2])
cv2.imshow("img", img)
cv2.setMouseCallback("img", print_cordinate)


(240, 427)
